services:

  my-app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - backend-network
    environment:
        SPRING_PROFILES_ACTIVE: docker
        DB_USER: postgres
        DB_PASS: 2202295
        JWT_SECRET: ${JWT_SECRET}
        JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:8
    ports:
      - "6380:6379"
    networks:
      - backend-network


  postgres:
    image: postgres:14.22-trixie
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2202295
      POSTGRES_DB: LoanDB
    ports:
      - 5430:5432
    volumes:
      - DB-volume:/var/lib/postgresql/data
    networks:
      - backend-network


networks:
  backend-network:

volumes:
  DB-volume: