name: CI
on:
  push:

jobs:
  build:
    env:
      DB_URL: jdbc:postgresql://localhost:5432/loan-system
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION_MS: ${{ secrets.JWT_EXPIRATION_MS }}
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.22-trixie
        env:
          POSTGRES_DB: loan-system
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 2202295
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4   # this line means "clone my repository"
      - uses: actions/setup-java@v4 # this line = "sudo apt install java"
        with:
          distribution: temurin
          java-version: 21
      - run: mvn clean verify